<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

namespace mod_selfselectadvanced;

use mod_selfselectadvanced\local\quota\allocator;
use stdClass;

/**
 * A team is seated the same way whatever its attribute values are CALLED.
 *
 * WHY THIS FILE EXISTS. Through 1.20 wave 3B the allocator's memo key was
 *
 *     slot . availability . dimension . value . value . ...
 *
 * with the attribute VALUES written into it, and the memo was bounded by
 * a budget in BYTES. Those two facts together made the search's budget
 * depend on how long a course's words are. A site that types
 * "Electronics and Communication Engineering" into the free-text
 * Department that attributes/csv_importer accepts - 41 characters - got
 * roughly a tenth of the remembered states that a site typing "eng" got
 * for exactly the same roster and exactly the same template, and the
 * shorter search then gave up and handed the team to the greedy
 * fallback, which reports a LOWER BOUND. The consequence reaches a
 * student: quota\slots::evaluate_from_data() turns the seats the
 * fallback did not fill into the team's shortfall, so a team that meets
 * its composition template is told it does not.
 *
 * Nothing noticed for a whole wave because both corpora that guard this
 * class - tests/allocator_memory_test.php and
 * tests/allocator_exactness_test.php - build every value as "gender3",
 * SEVEN characters, and put their wide end at 21 to 30 members. The
 * losses are at TWELVE members with long values, which neither reached.
 * Measured on the shapes below before the repair, the wave-3B build
 * seats eleven of twelve people when the values are seven characters
 * long and FIVE of them when the same values are 51 characters long.
 *
 * The repair is structural rather than another constant: allocator
 * interns the values to small integer ids at load and keys the memo on
 * the ids, so an entry's cost depends on the roster and the template and
 * not on the vocabulary. What this file pins is the property that buys -
 * that the four value lengths give ONE answer - and the answers
 * themselves, taken from the engine run with no memory budget at all.
 *
 * The corpus is generated by a private LCG rather than mt_rand(), so the
 * shapes are fixed for all time and do not move when PHP's RNG or
 * another test's seeding does. It is the same recurrence the two files
 * above use and it is deliberately duplicated rather than shared: a case
 * here must never change because a memory shape was retuned there.
 *
 * @package    mod_selfselectadvanced
 * @copyright  2026 JSP <jsp@jsp.net.in>
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @covers     \mod_selfselectadvanced\local\quota\allocator
 */
final class allocator_longvalues_test extends \advanced_testcase {
    /**
     * The value lengths every case is run at, in characters.
     *
     * Seven is what the two older corpora use. Fifty-one is not exotic:
     * "Electronics and Communication Engineering" is 41 characters and
     * the department fields are free text. 131 and 311 are there because
     * the defect grew with length and a corpus that stops at the first
     * length that fails proves less than one that does not.
     *
     * @var int[]
     */
    private const LENGTHS = [7, 51, 131, 311];

    /**
     * The ceiling one solve may allocate, in bytes.
     *
     * The same third of MEMORY_STANDARD that
     * tests/allocator_memory_test.php sanctions, repeated rather than
     * shared so that relaxing it there cannot quietly relax it here.
     *
     * @var int
     */
    private const CEILING = 43 * 1024 * 1024;

    /** @var int LCG state. */
    private int $lcg = 1;

    /**
     * Deterministic pseudo-random integer in [1, $max].
     *
     * @param int $max the inclusive upper bound
     * @return int the next value
     */
    private function next(int $max): int {
        $this->lcg = ($this->lcg * 1103515245 + 12345) & 0x7fffffff;

        return 1 + (int) ($this->lcg % $max);
    }

    /**
     * A value tag padded out to exactly $length characters.
     *
     * The tag is TWO characters - a letter for the dimension and a digit
     * for the value - and no case below uses more than nine values per
     * dimension, so every value in every dimension is the same length
     * and padding cannot change how two values compare. That is what
     * makes "the same case at four lengths" the SAME case, and it is the
     * one thing this generator has to get right: an earlier version
     * built the tag from the dimension NAME and truncated it to reach
     * seven characters, which silently collapsed department,
     * subdepartment and program to a single value each - not a
     * short-valued case, a different problem, and one that would have
     * made every assertion here meaningless.
     *
     * @param string $dimension the attribute dimension
     * @param int $n the value index, one to nine
     * @param int $length the length to pad to
     * @return string the padded value
     */
    private static function value(string $dimension, int $n, int $length): string {
        $tag = substr($dimension, 0, 1) . $n;

        return $length <= strlen($tag) ? $tag : $tag . ' ' . str_repeat('x', $length - strlen($tag) - 1);
    }

    /**
     * A roster of $members people carrying values of exactly $length
     * characters in each of the four attribute dimensions.
     *
     * @param int $members roster size
     * @param int $values distinct values per dimension, at most nine
     * @param int $length the length of every value, in characters
     * @return array [int[] userids, stdClass[] attribute records keyed by userid]
     */
    private function roster(int $members, int $values, int $length): array {
        $ids = [];
        $attrs = [];
        for ($userid = 1; $userid <= $members; $userid++) {
            $record = new stdClass();
            foreach (['gender', 'department', 'subdepartment', 'program'] as $dimension) {
                $record->{$dimension} = self::value($dimension, $this->next($values), $length);
            }
            $attrs[$userid] = $record;
            $ids[] = $userid;
        }

        return [$ids, $attrs];
    }

    /**
     * A template of $slots slots, each offering $seats seats, mixing
     * distinct slots, shared-value slots and fixed-value slots and
     * refusing overlap.
     *
     * @param int $slots slot count
     * @param int $seats seats per slot
     * @param int $values distinct values per dimension
     * @param int $length the length of every value, in characters
     * @return stdClass[] slot rows in template order
     */
    private function template(int $slots, int $seats, int $values, int $length): array {
        $dimensions = ['gender', 'department', 'subdepartment', 'program'];
        $rows = [];
        for ($i = 0; $i < $slots; $i++) {
            $dimension = $dimensions[$i % 4];
            $roll = $this->next(10);
            if ($roll <= 3) {
                $matchtype = 'distinct';
                $value = null;
            } else if ($roll <= 7) {
                $matchtype = 'value';
                $value = null;
            } else {
                $matchtype = 'value';
                $value = self::value($dimension, $this->next($values), $length);
            }
            $rows[] = (object) [
                'slotno' => $i + 1,
                'mincount' => $seats,
                'dimension' => $dimension,
                'matchtype' => $matchtype,
                'value' => $value,
                'allowoverlap' => 0,
            ];
        }

        return $rows;
    }

    /**
     * Build one generated case at a given value length.
     *
     * @param array $case [seed, members, slots, seats, values]
     * @param int $length the length of every value, in characters
     * @return array [stdClass[] template, int[] userids, stdClass[] attrs]
     */
    private function build(array $case, int $length): array {
        [$seed, $members, $slots, $seats, $values] = $case;
        $this->lcg = $seed;
        [$ids, $attrs] = $this->roster($members, $values, $length);
        $template = $this->template($slots, $seats, $values, $length);

        return [$template, $ids, $attrs];
    }

    /**
     * Solve one generated case at a given value length.
     *
     * @param array $case [seed, members, slots, seats, values]
     * @param int $length the length of every value, in characters
     * @return stdClass the allocator's result
     */
    private function solve(array $case, int $length): stdClass {
        [$template, $ids, $attrs] = $this->build($case, $length);

        return allocator::solve($template, $ids, $attrs);
    }

    /**
     * The cases, with the verdict each one MUST return at every length.
     *
     * Every expectation was produced by this engine run with its memory
     * budget removed entirely - the unbounded answer - so a budget that
     * starts truncating one of these fails here rather than quietly
     * reporting a team short. Five are the shapes the audit named, at
     * twelve members, which is where the wave-3B build lost seats; four
     * are at the wide end, twenty-six and thirty members, which is where
     * the older corpora already looked.
     *
     * The comment on each row is what the wave-3B build (string keys, an
     * entry ceiling and a byte budget) answers at 7 / 51 / 131 / 311
     * characters, measured. Six of the ten move, so those six rows are
     * what makes this file go red against that tree; the other four are
     * here for the shapes, not for the colour.
     *
     * @return array<string, array{array{int, int, int, int, int}, array{bool, int, int[], int[]}}>
     */
    public static function cases_provider(): array {
        return [
            // Wave-3B: 10/10/9/9, exact E/E/f/f - a seat lost at 131.
            '12 members, 10 three-seat rules' => [
                [2, 12, 10, 3, 6],
                // Distribution re-measured 2026-08-13 (most-constrained-first);
                // exact and totalfilled unchanged.
                [true, 10, [0, 0, 3, 1, 0, 3, 0, 1, 1, 1],
                    // Assignment re-measured 2026-08-13: same ten people seated,
                    // one of them in a different seat.
                    [1 => 2, 2 => 5, 4 => 5, 5 => 2, 7 => 3, 8 => 9, 9 => 5, 10 => 2, 11 => 7, 12 => 8]],
            ],
            // Wave-3B: 11/5/5/5, exact E/f/f/f - SIX seats lost at 51
            // characters, which is a compliant team reported six short.
            '12 members, 12 one-seat rules, five values' => [
                [1, 12, 12, 1, 5],
                [true, 11, [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                    [1 => 0, 2 => 10, 3 => 1, 4 => 5, 5 => 7, 6 => 9, 7 => 4, 8 => 8, 9 => 6, 10 => 11, 11 => 3]],
            ],
            // Wave-3B: 8/8/3/3, exact E/E/f/f - five seats lost at 131.
            '12 members, 12 one-seat rules, six values' => [
                [1, 12, 12, 1, 6],
                [true, 8, [1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
                    [3 => 9, 5 => 0, 7 => 8, 8 => 7, 9 => 10, 10 => 6, 11 => 11, 12 => 5]],
            ],
            // Wave-3B: 8/8/4/4, exact E/E/f/f - four seats lost at 131.
            '12 members, 8 two-seat rules, six values' => [
                [4, 12, 8, 2, 6],
                [true, 8, [2, 0, 1, 2, 1, 2, 0, 0],
                    [2 => 5, 3 => 0, 4 => 3, 5 => 3, 7 => 2, 9 => 0, 10 => 4, 11 => 5]],
            ],
            // Wave-3B: 11/11/11/8, exact E/E/E/f - three lost at 311.
            '12 members, 8 two-seat rules, five values' => [
                [1, 12, 8, 2, 5],
                // Re-measured 2026-08-13: eleven seated before and after; the
                // second seat now gets a member the sixth used to take.
                [true, 11, [2, 1, 0, 1, 2, 2, 2, 1],
                    [1 => 6, 2 => 4, 3 => 1, 4 => 5, 5 => 5, 6 => 0, 7 => 6, 8 => 7, 9 => 0, 11 => 3, 12 => 4]],
            ],
            // Wave-3B: 7/7/7/7 but exact E/f/f/f - no seat lost, yet the
            // caller is told the answer is not trustworthy purely
            // because the words got longer.
            '30 members, 8 one-seat rules' => [
                [1, 30, 8, 1, 6],
                [true, 7, [1, 1, 1, 0, 1, 1, 1, 1],
                    [2 => 6, 3 => 1, 14 => 2, 21 => 7, 24 => 4, 25 => 0, 28 => 5]],
            ],
            // Wave-3B: 4/4/4/4, exact E/E/E/E - unmoved, and here for
            // the thirty-member shape rather than for the colour.
            '30 members, 10 two-seat rules' => [
                [1, 30, 10, 2, 8],
                [true, 4, [2, 2, 0, 0, 0, 0, 0, 0, 0, 0], [1 => 1, 2 => 0, 3 => 1, 4 => 0]],
            ],
            // The NODE budget, not the memory budget, decides these
            // three: they are answered by the greedy fallback at every
            // length. Pinned because a fallback nobody pins is a
            // heuristic that can change without a test noticing, and
            // because the fallback's answer must not move with the
            // vocabulary either.
            '30 members, 12 two-seat rules (falls back)' => [
                [2, 30, 12, 2, 5],
                [false, 17, [2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0],
                    [1 => 5, 2 => 2, 3 => 4, 4 => 6, 5 => 5, 6 => 7, 7 => 0, 8 => 2, 9 => 8, 10 => 1,
                        11 => 6, 12 => 4, 13 => 1, 16 => 0, 17 => 7, 23 => 3, 26 => 3]],
            ],
            '30 members, 12 one-seat rules (falls back)' => [
                [1, 30, 12, 1, 6],
                [false, 7, [1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0],
                    [1 => 0, 2 => 6, 3 => 4, 4 => 1, 5 => 5, 14 => 2, 21 => 7]],
            ],
            '26 members, 12 one-seat rules (falls back)' => [
                [1, 26, 12, 1, 6],
                [false, 7, [1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0],
                    [1 => 7, 2 => 0, 3 => 1, 6 => 5, 8 => 4, 9 => 2, 12 => 8]],
            ],
        ];
    }

    /**
     * The generator builds the SAME case at every length.
     *
     * Asserted before anything is concluded from it, because the whole
     * file is worthless if it is not true: every value is exactly as
     * long as asked, every dimension carries the same number of distinct
     * values at every length, and the same people carry the same values
     * as each other. A corpus that quietly collapses its values at the
     * short end would make the four lengths four different problems and
     * every "the answer did not move" assertion below a tautology.
     */
    public function test_the_generator_builds_one_case_at_four_lengths(): void {
        $dimensions = ['gender', 'department', 'subdepartment', 'program'];
        foreach (self::cases_provider() as $name => [$case, $unusedexpected]) {
            $signature = null;
            foreach (self::LENGTHS as $length) {
                [$template, $ids, $attrs] = $this->build($case, $length);
                $distinct = [];
                $shape = [];
                foreach ($ids as $userid) {
                    foreach ($dimensions as $dimension) {
                        $value = $attrs[$userid]->{$dimension};
                        $this->assertSame(
                            $length,
                            strlen($value),
                            "$name: a $dimension value is not $length characters long"
                        );
                        $distinct[$dimension][$value] = true;
                        // The value's IDENTITY, stripped of the padding,
                        // so the four lengths can be compared directly.
                        $shape[] = substr($value, 0, 2);
                    }
                }
                foreach ($template as $slot) {
                    $shape[] = $slot->matchtype . ':' . $slot->dimension . ':' . $slot->mincount . ':'
                        . ($slot->value === null ? '-' : substr($slot->value, 0, 2));
                    if ($slot->value !== null) {
                        $this->assertSame($length, strlen($slot->value), "$name: a slot value is short");
                    }
                }
                $counts = array_map('count', $distinct);
                $signature ??= [$shape, $counts];
                $this->assertSame(
                    $signature,
                    [$shape, $counts],
                    "$name: the case at $length characters is not the same case as at " . self::LENGTHS[0]
                );
            }
        }
    }

    /**
     * The verdict does not depend on how long the attribute values are.
     *
     * This is the whole point of interning the values, and it is the
     * assertion the wave-3B build fails on six of the ten cases: there
     * the same roster and the same template are seated one way when the
     * words are seven characters long and another way when they are 51.
     * A team's compliance may not turn on a course's vocabulary.
     */
    public function test_the_answer_does_not_depend_on_how_long_the_values_are(): void {
        foreach (self::cases_provider() as $name => [$case, $unusedexpected]) {
            $first = $this->solve($case, self::LENGTHS[0]);
            foreach (array_slice(self::LENGTHS, 1) as $length) {
                $result = $this->solve($case, $length);
                $this->assertSame(
                    $first->exact,
                    $result->exact,
                    "$name: exactness moved between " . self::LENGTHS[0] . " and $length characters"
                );
                $this->assertSame(
                    $first->totalfilled,
                    $result->totalfilled,
                    "$name: the fill moved between " . self::LENGTHS[0] . " and $length characters - "
                        . 'a team is seated differently because its course names things at length'
                );
                $this->assertSame($first->filled, $result->filled, "$name: the seating moved at $length");
                $this->assertSame($first->assignment, $result->assignment, "$name: the people moved at $length");
            }
        }
    }

    /**
     * And the answer at every length is the UNBOUNDED answer.
     *
     * Invariance alone is satisfied by an engine that is wrong the same
     * way four times over, so the four lengths are checked against the
     * verdict this engine returns with no memory budget at all rather
     * than only against each other.
     */
    public function test_a_long_keyed_roster_is_seated_the_way_an_unbounded_search_seats_it(): void {
        foreach (self::cases_provider() as $name => [$case, [$exact, $totalfilled, $filled, $assignment]]) {
            foreach (self::LENGTHS as $length) {
                $result = $this->solve($case, $length);
                $where = "$name at $length characters";
                $this->assertSame($exact, $result->exact, "exactness moved on $where");
                $this->assertSame($totalfilled, $result->totalfilled, "the fill moved on $where");
                $this->assertSame($filled, $result->filled, "the seating moved on $where");
                $this->assertSame($assignment, $result->assignment, "the people moved on $where");
                // Whatever the verdict, the answer is a real seating.
                $this->assertSame($totalfilled, array_sum($result->filled));
                $this->assertCount($totalfilled, $result->assignment);
                $this->assertSame(array_keys($result->assignment), array_unique(array_keys($result->assignment)));
            }
        }
    }

    /**
     * The corpus reaches the fallback, and reaching it under-reports.
     *
     * A file that only ever exercised searches which finish would prove
     * nothing about the giving-up path, so three of the cases above are
     * decided by the greedy fallback - the NODE budget, which is the
     * budget that binds inside the input-size guard once the keys are
     * interned. Their fills are asserted to be no larger than what the
     * exact search reaches on the same shape, which is the fail-CLOSED
     * property the whole budget design rests on: a truncated run may
     * under-report a team and may never call a non-compliant team
     * compliant.
     */
    public function test_the_corpus_reaches_the_fallback_and_the_fallback_under_reports(): void {
        $fellback = 0;
        foreach (self::cases_provider() as $name => [$case, [$exact, $totalfilled, $unusedfilled, $unusedassignment]]) {
            if ($exact) {
                continue;
            }
            $fellback++;
            foreach (self::LENGTHS as $length) {
                $result = $this->solve($case, $length);
                $this->assertFalse($result->exact, "$name at $length characters no longer reaches a budget");
                $this->assertSame($totalfilled, $result->totalfilled, "$name: the fallback answer moved at $length");
                // A seating the fallback reports must be one it can
                // actually make: nobody seated twice, and the numbers
                // agreeing with each other.
                $this->assertSame($result->totalfilled, array_sum($result->filled));
                $this->assertCount($result->totalfilled, $result->assignment);
                $this->assertLessThanOrEqual($case[1], $result->totalfilled, "$name: more seats filled than people");
            }
        }
        $this->assertGreaterThan(
            0,
            $fellback,
            'no case reaches a budget any more, so the giving-up path is untested here'
        );
    }

    /**
     * Long values cost the SEARCH nothing, in memory as well as in seats.
     *
     * Two things are measured, because either one alone can be passed by
     * something broken.
     *
     * THE GAP. The same case at seven characters and at 311 must cost
     * the same memory to within two megabytes. Measured on the wave-3B
     * build the two differ by 29.2 MB on this shape - 5.5 MB against
     * 34.7 - because the long-valued run filled its byte budget with
     * vocabulary and was truncated where the short-valued one ran to the
     * end. Measured on this build they differ by 0.02 MB, which is the
     * attribute strings themselves and nothing else.
     *
     * THE CEILING. A gap of zero is also what an engine that spends 200
     * MB at both lengths would show, so the widest long-valued case in
     * the table - twenty-six members over twelve rules, the most
     * expensive solve measured anywhere in this file at 31.1 MB - is
     * required to stay inside the envelope one solve is allowed.
     */
    public function test_a_long_keyed_solve_stays_inside_the_memory_envelope(): void {
        $peaks = [];
        foreach ([[1, 12, 8, 2, 5], [1, 26, 12, 1, 6]] as $case) {
            foreach ([7, 311] as $length) {
                [$template, $ids, $attrs] = $this->build($case, $length);
                gc_collect_cycles();
                memory_reset_peak_usage();
                $before = memory_get_peak_usage(false);
                allocator::solve($template, $ids, $attrs);
                $peak = memory_get_peak_usage(false) - $before;
                $peaks[implode(',', $case)][$length] = $peak;
                $this->assertLessThan(
                    self::CEILING,
                    $peak,
                    sprintf(
                        'one solve of [%s] at %d-character values allocated %.1f MB; MEMORY_STANDARD is '
                            . '128 MB and no entry point raises it',
                        implode(',', $case),
                        $length,
                        $peak / 1048576
                    )
                );
            }
        }

        foreach ($peaks as $case => $bylength) {
            $this->assertLessThan(
                2 * 1024 * 1024,
                abs($bylength[311] - $bylength[7]),
                sprintf(
                    '[%s] cost %.1f MB at 7-character values and %.1f MB at 311, so the memo is still '
                        . 'paying for the vocabulary',
                    $case,
                    $bylength[7] / 1048576,
                    $bylength[311] / 1048576
                )
            );
        }
    }
}
