<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

namespace mod_selfselectadvanced;

use mod_selfselectadvanced\local\quota\allocator;
use stdClass;

/**
 * The seat allocator's MEMORY envelope (audit O-4).
 *
 * The allocator's failure mode at the input-size guard's boundary was
 * never a slow page: it was a FATAL. Nothing on the way in raises the
 * memory limit - not search_groups (one solve per team, per keystroke),
 * not joinrequest.php, not flagged.php's whole-activity sweep - so a
 * solve gets Moodle's MEMORY_STANDARD, 128 MB on 64-bit, minus whatever
 * the request has already spent. Measured before the repair, one
 * thirty-member twelve-slot template allocated 169 MB on its own.
 *
 * These tests EXERCISE allocator::solve() on adversarial templates at
 * the guard boundary and measure what it actually allocates; nothing
 * here restates the class's arithmetic. They are deliberately built to
 * reach the fallback, and they ASSERT that they reached it - a memory
 * ceiling that no run came near would be a green check that examined
 * nothing.
 *
 * The corpus is generated by a private LCG rather than mt_rand(), so
 * the shapes are fixed for all time and do not move when PHP's RNG or
 * another test's seeding does.
 *
 * @package    mod_selfselectadvanced
 * @copyright  2026 JSP <jsp@jsp.net.in>
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @covers     \mod_selfselectadvanced\local\quota\allocator
 */
final class allocator_memory_test extends \advanced_testcase {
    /**
     * The ceiling one solve may allocate, in bytes.
     *
     * A third of MEMORY_STANDARD (128 MB), which leaves the two thirds
     * a Moodle page actually needs. The worst case measured over the
     * 680-case corpus behind allocator::MAX_MEMO is 41 MB, so this is
     * roughly a fifty per cent allowance over the worst known shape and
     * still less than a third of the limit that would kill the request.
     *
     * @var int
     */
    private const CEILING = 43 * 1024 * 1024;

    /** @var int LCG state. */
    private int $lcg = 1;

    /**
     * Deterministic pseudo-random integer in [1, $max].
     *
     * @param int $max the inclusive upper bound
     * @return int the next value
     */
    private function next(int $max): int {
        $this->lcg = ($this->lcg * 1103515245 + 12345) & 0x7fffffff;

        return 1 + (int) ($this->lcg % $max);
    }

    /**
     * A roster of $members people carrying random values in each of the
     * four attribute dimensions.
     *
     * @param int $members roster size
     * @param int $values distinct values per dimension
     * @return array [int[] userids, stdClass[] attribute records keyed by userid]
     */
    private function roster(int $members, int $values): array {
        $ids = [];
        $attrs = [];
        for ($userid = 1; $userid <= $members; $userid++) {
            $record = new stdClass();
            foreach (['gender', 'department', 'subdepartment', 'program'] as $dimension) {
                $record->{$dimension} = $dimension . $this->next($values);
            }
            $attrs[$userid] = $record;
            $ids[] = $userid;
        }

        return [$ids, $attrs];
    }

    /**
     * A template of $slots slots, each offering $seats seats, mixing
     * distinct slots, shared-value slots and fixed-value slots and
     * refusing overlap - the shape that makes the search space large.
     *
     * @param int $slots slot count
     * @param int $seats seats per slot
     * @param int $values distinct values per dimension
     * @return stdClass[] slot rows in template order
     */
    private function template(int $slots, int $seats, int $values): array {
        $dimensions = ['gender', 'department', 'subdepartment', 'program'];
        $rows = [];
        for ($i = 0; $i < $slots; $i++) {
            $dimension = $dimensions[$i % 4];
            $roll = $this->next(10);
            if ($roll <= 3) {
                $matchtype = 'distinct';
                $value = null;
            } else if ($roll <= 7) {
                $matchtype = 'value';
                $value = null;
            } else {
                $matchtype = 'value';
                $value = $dimension . $this->next($values);
            }
            $rows[] = (object) [
                'slotno' => $i + 1,
                'mincount' => $seats,
                'dimension' => $dimension,
                'matchtype' => $matchtype,
                'value' => $value,
                'allowoverlap' => 0,
            ];
        }

        return $rows;
    }

    /**
     * Solve one generated case and report what it cost.
     *
     * @param int $seed the LCG seed
     * @param int $members roster size
     * @param int $slots slot count
     * @param int $seats seats per slot
     * @param int $values distinct values per dimension
     * @return array [stdClass result, int peak bytes allocated by the solve]
     */
    private function measure(int $seed, int $members, int $slots, int $seats, int $values): array {
        $this->lcg = $seed;
        [$ids, $attrs] = $this->roster($members, $values);
        $template = $this->template($slots, $seats, $values);

        gc_collect_cycles();
        memory_reset_peak_usage();
        $before = memory_get_peak_usage(false);
        $result = allocator::solve($template, $ids, $attrs);
        $peak = memory_get_peak_usage(false) - $before;

        return [$result, $peak];
    }

    /**
     * The guard boundary, which is where the fatal lived: thirty
     * members (MAX_MEMBERS) against slot counts and seat counts right
     * up against MAX_SLOTS and MAX_SEATS, on templates built to make
     * the search thrash.
     *
     * Every one of these shapes is INSIDE the input-size guard, so the
     * exact search runs and the memory is really spent. The assertion
     * is on bytes allocated, and a second assertion proves the corpus
     * is doing its job: at least one of these runs must actually
     * exhaust the budget, or the ceiling is being cleared by a search
     * that never got going.
     */
    public function test_the_guard_boundary_stays_inside_the_envelope(): void {
        $shapes = [
            [30, 8, 5, 8],
            [30, 12, 3, 6],
            [30, 10, 4, 5],
            [30, 12, 3, 4],
            [28, 12, 2, 3],
            [24, 12, 2, 5],
        ];

        $worst = 0;
        $worstshape = '';
        $fellback = 0;
        foreach ($shapes as [$members, $slots, $seats, $values]) {
            for ($seed = 1; $seed <= 3; $seed++) {
                [$result, $peak] = $this->measure($seed, $members, $slots, $seats, $values);
                if (!$result->exact) {
                    $fellback++;
                }
                // Whatever it cost, the answer must still be a real
                // seating: nobody seated twice, nobody in a slot that
                // does not exist, and the count agreeing with itself.
                $this->assertCount($result->totalfilled, $result->assignment);
                $this->assertSame(array_unique(array_keys($result->assignment)), array_keys($result->assignment));
                foreach ($result->assignment as $slotindex) {
                    $this->assertGreaterThanOrEqual(0, $slotindex);
                    $this->assertLessThan($slots, $slotindex);
                }
                if ($peak > $worst) {
                    $worst = $peak;
                    $worstshape = "members=$members slots=$slots seats=$seats values=$values seed=$seed";
                }
            }
        }

        $this->assertGreaterThan(
            0,
            $fellback,
            'the corpus no longer stresses the search, so the ceiling below is proving nothing'
        );
        $this->assertLessThan(
            self::CEILING,
            $worst,
            sprintf(
                'one solve allocated %.1f MB (%s); MEMORY_STANDARD is 128 MB and no entry point raises it',
                $worst / 1048576,
                $worstshape
            )
        );
    }

    /**
     * Giving up is FAIL-CLOSED, whichever half of the budget ran out.
     *
     * The greedy fallback's booking is a valid seating under the same
     * constraints, so its fill is a lower bound on the exact answer:
     * exhausting the budget may under-report a team and can never call
     * a non-compliant team compliant. Asserted by seating a roster that
     * plainly cannot fill the template and checking the fallback does
     * not invent seats.
     */
    public function test_exhausting_the_budget_never_overstates_the_fill(): void {
        [$result, $peak] = $this->measure(1, 30, 12, 3, 6);

        $this->assertFalse($result->exact, 'this shape is the one that exhausts the budget');
        $this->assertLessThan(self::CEILING, $peak);
        // Thirty-six seats offered, thirty members: the fill can never
        // exceed the roster, and every named person holds exactly one
        // seat.
        $this->assertLessThanOrEqual(30, $result->totalfilled);
        $this->assertSame($result->totalfilled, array_sum($result->filled));
        $this->assertCount($result->totalfilled, $result->assignment);
    }

    /**
     * The two halves of the budget are BOTH honoured, and the memory
     * half is the one that has a ceiling: no run may file more memo
     * entries than MAX_MEMO, whatever the node budget would allow.
     *
     * Exercised through solve() on a shape that reaches the cap - there
     * is no way to observe the memo from outside, and there should not
     * be - so this asserts the consequence: the run gives up rather
     * than growing, and gives up deterministically, the same answer
     * twice.
     */
    public function test_the_memory_budget_is_deterministic(): void {
        $this->assertLessThanOrEqual(
            allocator::MAX_NODES,
            allocator::MAX_MEMO,
            'a memo cap above the node budget could never bind and would be decoration'
        );

        [$first] = $this->measure(2, 30, 10, 4, 5);
        [$second] = $this->measure(2, 30, 10, 4, 5);

        $this->assertFalse($first->exact);
        $this->assertEquals($first, $second, 'two runs over identical data disagreed');
    }
}
