<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

namespace mod_selfselectadvanced;

use mod_selfselectadvanced\local\quota\allocator;
use stdClass;

/**
 * The seat allocator's VERDICTS, pinned against the engine that decided
 * them before the memo was packed (wave-3B audit, G-1).
 *
 * WHY THIS FILE EXISTS. tests/allocator_memory_test.php asserts BYTES.
 * It never compared an ANSWER against the engine the packed-memo
 * rewrite replaced, and so nothing in the repository noticed when a
 * memo ceiling introduced for memory turned a team that seats seven
 * people into a team reported as seating five. The ceiling is
 * fail-CLOSED, so the damage is silent by construction: the fill is
 * under-reported, `exact` goes false, quota\slots::evaluate_from_data()
 * copies the shortfall through, and a COMPLIANT team is told it is not
 * - which is precisely the defect commit b6ff326 was written to remove.
 * A budget that trades correctness for memory has to be pinned by
 * something that reads the correctness.
 *
 * The expectations below are not a snapshot of this engine. Every one
 * of them was produced by running the PRE-REWRITE allocator
 * (dd2898c~1, the class renamed so both engines can be loaded at once)
 * over the same generated case, and the two agree on filled,
 * assignment, totalfilled and exact - which is the property the rewrite
 * claimed and the ceiling had quietly broken.
 *
 * The corpus is generated by a private LCG rather than mt_rand(), so
 * the shapes are fixed for all time and do not move when PHP's RNG or
 * another test's seeding does. It is the same generator
 * allocator_memory_test.php uses, deliberately duplicated rather than
 * shared: a case here must never change because a memory shape was
 * retuned there.
 *
 * @package    mod_selfselectadvanced
 * @copyright  2026 JSP <jsp@jsp.net.in>
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @covers     \mod_selfselectadvanced\local\quota\allocator
 */
final class allocator_exactness_test extends \advanced_testcase {
    /** @var int LCG state. */
    private int $lcg = 1;

    /**
     * Deterministic pseudo-random integer in [1, $max].
     *
     * @param int $max the inclusive upper bound
     * @return int the next value
     */
    private function next(int $max): int {
        $this->lcg = ($this->lcg * 1103515245 + 12345) & 0x7fffffff;

        return 1 + (int) ($this->lcg % $max);
    }

    /**
     * A roster of $members people carrying random values in each of the
     * four attribute dimensions.
     *
     * @param int $members roster size
     * @param int $values distinct values per dimension
     * @return array [int[] userids, stdClass[] attribute records keyed by userid]
     */
    private function roster(int $members, int $values): array {
        $ids = [];
        $attrs = [];
        for ($userid = 1; $userid <= $members; $userid++) {
            $record = new stdClass();
            foreach (['gender', 'department', 'subdepartment', 'program'] as $dimension) {
                $record->{$dimension} = $dimension . $this->next($values);
            }
            $attrs[$userid] = $record;
            $ids[] = $userid;
        }

        return [$ids, $attrs];
    }

    /**
     * A template of $slots slots, each offering $seats seats, mixing
     * distinct slots, shared-value slots and fixed-value slots and
     * refusing overlap.
     *
     * @param int $slots slot count
     * @param int $seats seats per slot
     * @param int $values distinct values per dimension
     * @return stdClass[] slot rows in template order
     */
    private function template(int $slots, int $seats, int $values): array {
        $dimensions = ['gender', 'department', 'subdepartment', 'program'];
        $rows = [];
        for ($i = 0; $i < $slots; $i++) {
            $dimension = $dimensions[$i % 4];
            $roll = $this->next(10);
            if ($roll <= 3) {
                $matchtype = 'distinct';
                $value = null;
            } else if ($roll <= 7) {
                $matchtype = 'value';
                $value = null;
            } else {
                $matchtype = 'value';
                $value = $dimension . $this->next($values);
            }
            $rows[] = (object) [
                'slotno' => $i + 1,
                'mincount' => $seats,
                'dimension' => $dimension,
                'matchtype' => $matchtype,
                'value' => $value,
                'allowoverlap' => 0,
            ];
        }

        return $rows;
    }

    /**
     * Solve one generated case.
     *
     * @param int $seed the LCG seed
     * @param int $members roster size
     * @param int $slots slot count
     * @param int $seats seats per slot
     * @param int $values distinct values per dimension
     * @return stdClass the allocator's result
     */
    private function solve(int $seed, int $members, int $slots, int $seats, int $values): stdClass {
        $this->lcg = $seed;
        [$ids, $attrs] = $this->roster($members, $values);
        $template = $this->template($slots, $seats, $values);

        return allocator::solve($template, $ids, $attrs);
    }

    /**
     * The two shapes the memo ceiling used to cost a seat on.
     *
     * Both are INSIDE the input-size guard and both are ordinary: nine
     * members against eight four-seat rules, and fourteen members
     * against nine single-seat rules. Before the ceiling was derived
     * from the memory budget rather than from a sample, the first was
     * still seated correctly but was reported INEXACT - so a caller
     * could not trust it - and the second lost two seats outright,
     * reporting a fill of five where seven people can in fact be
     * seated.
     *
     * The assignment is asserted as well as the fill, because it is the
     * assignment that proves the search reached the same optimum rather
     * than a different one of the same size: the docblock promises the
     * shortfall lands on the most restrictive seats and that the answer
     * never depends on exploration order, and only pinning the named
     * people tests that promise.
     */
    public function test_the_memo_ceiling_never_costs_a_seat(): void {
        $result = $this->solve(224, 9, 8, 4, 3);
        $this->assertTrue(
            $result->exact,
            'nine members over eight rules gave up before it was out of memory'
        );
        $this->assertSame(9, $result->totalfilled);
        $this->assertSame([4, 3, 2, 0, 0, 0, 0, 0], $result->filled);
        $this->assertSame(
            [1 => 2, 2 => 0, 3 => 0, 4 => 2, 5 => 0, 6 => 1, 7 => 0, 8 => 1, 9 => 1],
            $result->assignment
        );

        $result = $this->solve(649, 14, 9, 1, 6);
        $this->assertTrue(
            $result->exact,
            'fourteen members over nine rules gave up before it was out of memory'
        );
        $this->assertSame(
            7,
            $result->totalfilled,
            'seven of these fourteen can be seated; a smaller number is a compliant team called non-compliant'
        );
        $this->assertSame([1, 1, 1, 1, 1, 0, 0, 1, 1], $result->filled);
        $this->assertSame(
            [1 => 0, 4 => 8, 6 => 7, 7 => 4, 10 => 2, 13 => 3, 14 => 1],
            $result->assignment
        );
    }

    /**
     * A verdict table, so a future budget change cannot move an answer
     * without a test noticing.
     *
     * Eight of these cases are decided EXACTLY and the memo they need
     * spans two orders of magnitude - sixteen entries for the smallest,
     * a hundred and twenty-two thousand for the largest - so lowering
     * either half of the memory budget shows up here as a verdict, not
     * as a byte count. The ninth case exhausts the NODE budget on both
     * engines and is included for exactly that reason: the fallback's
     * answer has to be pinned too, or a change to the greedy heuristic
     * is invisible.
     *
     * Every row was produced by the pre-rewrite engine and every row
     * agrees with this one.
     */
    public function test_the_verdict_table_has_not_moved(): void {
        // Key [seed, members, slots, seats, values], value [exact, totalfilled, filled].
        $cases = [
            [[224, 9, 8, 4, 3], [true, 9, [4, 3, 2, 0, 0, 0, 0, 0]]],
            [[649, 14, 9, 1, 6], [true, 7, [1, 1, 1, 1, 1, 0, 0, 1, 1]]],
            [[311, 12, 11, 2, 6], [true, 9, [0, 2, 2, 2, 0, 1, 0, 0, 0, 2, 0]]],
            [[292, 9, 12, 1, 5], [true, 8, [1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1]]],
            [[28, 29, 4, 3, 3], [true, 10, [2, 2, 3, 3]]],
            [[543, 24, 7, 2, 6], [true, 8, [2, 0, 2, 0, 2, 0, 2]]],
            [[53, 10, 9, 3, 6], [true, 9, [0, 1, 3, 2, 0, 1, 2, 0, 0]]],
            [[1, 12, 6, 2, 4], [true, 2, [2, 0, 0, 0, 0, 0]]],
            [[99, 6, 3, 2, 3], [true, 5, [2, 2, 1]]],
            [[7, 20, 5, 3, 5], [false, 12, [3, 3, 1, 3, 2]]],
        ];

        foreach ($cases as [[$seed, $members, $slots, $seats, $values], [$exact, $totalfilled, $filled]]) {
            $where = "seed=$seed members=$members slots=$slots seats=$seats values=$values";
            $result = $this->solve($seed, $members, $slots, $seats, $values);
            $this->assertSame($exact, $result->exact, "exactness moved on $where");
            $this->assertSame($totalfilled, $result->totalfilled, "the fill moved on $where");
            $this->assertSame($filled, $result->filled, "the seating moved on $where");
            // Whatever the verdict, the answer is a real seating.
            $this->assertSame($totalfilled, array_sum($result->filled));
            $this->assertCount($totalfilled, $result->assignment);
            $this->assertSame(array_keys($result->assignment), array_unique(array_keys($result->assignment)));
        }
    }

    /**
     * The memory budget is a COUNTER over the data, so two runs over
     * identical inputs return identical answers.
     *
     * There is one memory budget as of 2026-08-02 - MAX_MEMO_BYTES. The
     * entry ceiling that used to stand beside it was deleted when a memo
     * entry became a bounded size; this test named "both halves" until
     * then.
     *
     * This is the property the pre-lock composition check and the
     * in-lock re-check depend on: a budget that read the clock, or the
     * process's own memory_get_usage(), would let the same roster pass
     * the gate and then fail the commit, because both of those depend
     * on what the CALLER already spent. Asserted on a case that
     * actually reaches the ceiling, so the ceiling is on the path being
     * tested.
     *
     * TWO THINGS THIS TEST LEARNED THE HARD WAY (wave-3B prover), and
     * both are why it is written the way it is rather than as the two
     * lines it started as.
     *
     * The ballast is SCALED to the budget instead of being a fixed
     * range(1, 200000), which is about 8 MB. Replacing the byte budget
     * with `memory_get_usage() > N` - a reading of the process, the
     * exact thing this test is named for - left it green at every
     * threshold tried, because 8 MB is not enough to move a budget
     * measured in tens of megabytes across it. The footprint now grows
     * by MORE than MAX_MEMO_BYTES between the two runs, so any budget
     * comparing a reading against a memo-sized figure lands on
     * different sides of it.
     *
     * And the second run is asserted against the KNOWN answer as well
     * as against the first. Equality alone is satisfied by two runs that
     * are wrong in the same way - which is what a reading-based budget
     * does once the reading is over its threshold for both of them.
     */
    public function test_the_budget_is_a_counter_and_not_a_reading(): void {
        $first = $this->solve(649, 14, 9, 1, 6);
        $this->assertTrue($first->exact, 'fixture: this case must be decided exactly to start with');
        $this->assertSame(7, $first->totalfilled);

        // Grow the process footprint by more than the whole memo
        // budget, so a budget that READ that footprint cannot answer
        // the same way twice. Scaled to the constant on purpose: a
        // fixed ballast stops being enough the moment the budget moves.
        $target = memory_get_usage() + allocator::MAX_MEMO_BYTES + (4 * 1024 * 1024);
        $ballast = [];
        while (memory_get_usage() < $target) {
            $ballast[] = str_repeat('b', 4096);
        }
        $this->assertGreaterThan(
            allocator::MAX_MEMO_BYTES,
            memory_get_usage() - ($target - allocator::MAX_MEMO_BYTES - (4 * 1024 * 1024)),
            'fixture: the footprint did not actually grow past the budget'
        );

        $second = $this->solve(649, 14, 9, 1, 6);
        unset($ballast);

        // Against the known answer FIRST: two runs that are wrong in
        // the same way are equal to each other.
        $this->assertTrue(
            $second->exact,
            'the same roster was decided exactly, then inexactly, on nothing but a bigger process'
        );
        $this->assertSame(7, $second->totalfilled, 'the fill moved when only the CALLER had changed');
        $this->assertEquals($first, $second, 'two runs over identical data disagreed');
    }
}
